# 项目相关配置
cps:
  # 名称
  name: cps
  # 版本
  version: 4.7.5
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/cps/uploadPath，Linux配置 /home/cps/uploadPath）
  profile: /Users/bubu/Documents/Code/Java/cps-fabric/cps/uploadPath
  # 获取ip地址开关
  addressEnabled: true
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /cps
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# 日志配置
logging:
  level:
    com.cps: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  output:
    ansi:
      enabled: always
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cps.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


  # PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey:
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: 5
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  rememberMe:
    # 是否开启记住我
    enabled: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

#fabric相关:
#Org1:
#Org1组织管理员admin用户私钥的路径
keyFolderPath: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore
#Org1组织管理员admin用户私钥的值
keyFileName: d46688b43610e374d34606d8628584a71ec4e0df01301b10a60cfdc88cca7299_sk
#Org1组织管理员admin的身份验证证书的路径
certFolderPath: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/admincerts
#Org1组织管理员admin的身份验证证书的值
certFileName: Admin@org1.example.com-cert.pem

#order的tls的证书路径
tlsOrderFilePath: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem
#peer0的org1的tls的证书路径
tlsPeerFilePath: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
#peer1的org1的tls的证书路径
tlsPeerFilePathAddition: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

#Org2:
#Org2组织管理员admin用户私钥的路径
keyFolderPath2: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore
#Org2组织管理员admin用户私钥的值
keyFileName2: 0e01347c26442c6c8910b155b658a2d2a6411ea215359127ebbb0f4c12697c32_sk
#Org2组织管理员admin的身份验证证书的路径
certFolderPath2: /Users/bubu/Documents/Code/Java/cps-fabric/cps/cps-fabric/src/main/resources/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/admincerts
#Org2组织管理员admin的身份验证证书的值
certFileName2: Admin@org2.example.com-cert.pem

#order节点信息
orderName: orderer.example.com
orderGrpc: grpcs://orderer.example.com:7050

#peer节点信息
peer0Name: peer0.org1.example.com
peer0Grpc: grpcs://peer0.org1.example.com:7051
peer1Name: peer1.org1.example.com
peer1Grpc: grpcs://peer1.org1.example.com:8051

peer0Name2: peer0.org2.example.com
peer0Grpc2: grpcs://peer0.org2.example.com:9051
peer1Name2: peer1.org2.example.com
peer1Grpc2: grpcs://peer1.org2.example.com:10051